# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres:14.5-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123Pass
      - POSTGRES_DB=pizzadb
    ports:
      - '5432:5432'